# Generated by Django 5.2 on 2025-08-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contest_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
    ]
