# Generated by Django 5.2 on 2025-08-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_contest_image_newsarticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='contest_videos/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/', verbose_name='Видео'),
        ),
    ]
