# Generated by Django 5.2 on 2025-08-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_contest_video_newsarticle_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение (ссылка)'),
        ),
        migrations.AddField(
            model_name='contest',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео (ссылка)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение (ссылка)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео (ссылка)'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contest_images/', verbose_name='Изображение (файл)'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='contest_videos/', verbose_name='Видео (файл)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение (файл)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/', verbose_name='Видео (файл)'),
        ),
    ]
