# Generated by Django 5.2 on 2025-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_contest_image_url_contest_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Видео (ссылка)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Видео (ссылка)'),
        ),
    ]
