# Generated by Django 5.2 on 2025-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsarticle_options_alter_contest_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Изображение (ссылка)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Изображение (ссылка)'),
        ),
    ]
