# Generated by Django 5.2 on 2025-08-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_remove_teacher_contacts_teacher_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_full_name', models.CharField(max_length=255, verbose_name='ФИО ребёнка')),
                ('child_date_of_birth', models.DateField(verbose_name='Дата рождения ребёнка')),
                ('parent_full_name', models.CharField(max_length=255, verbose_name='ФИО родителя')),
                ('parent_contact_phone', models.CharField(max_length=20, verbose_name='Телефон родителя')),
                ('parent_contact_email', models.EmailField(max_length=254, verbose_name='Email родителя')),
                ('pfdo_certificate_number', models.CharField(max_length=50, verbose_name='Номер сертификата ПФДО')),
                ('school', models.CharField(max_length=255, verbose_name='Школа')),
                ('grade', models.CharField(max_length=50, verbose_name='Класс')),
                ('school_shift', models.CharField(max_length=50, verbose_name='Смена в школе')),
                ('message', models.TextField(blank=True, verbose_name='Дополнительное сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program', verbose_name='Выбранная программа')),
            ],
            options={
                'verbose_name': 'Заявка на запись',
                'verbose_name_plural': 'Заявки на запись',
                'ordering': ['-created_at'],
            },
        ),
    ]
