# Generated by Django 5.2 on 2025-08-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название занятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('day_of_week', models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Кабинет')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program', verbose_name='Программа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Запись расписания',
                'verbose_name_plural': 'Записи расписания',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
