# Generated by Django 5.2 on 2025-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Локация'),
        ),
    ]
