# Generated by Django 5.2 on 2025-08-16 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name='Опыт работы')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_group', models.CharField(max_length=50, verbose_name='Возрастная группа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
    ]
