# Generated by Django 5.2 on 2025-08-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='contacts',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_messenger',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MAX-мессенджер'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='other_contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Другие контакты'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram_messenger',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
    ]
